# Generated by Django 4.1.3 on 2023-01-14 17:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_secret_answer_customuser_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date]),
        ),
    ]
