# Generated by Django 4.1.3 on 2023-01-14 19:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=core.models.user_profile_photo_path),
        ),
    ]
