"""initial

Revision ID: 96c49bcfcfbc
Revises: 8a295310fb8a
Create Date: 2022-10-07 14:33:37.020519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c49bcfcfbc'
down_revision = '8a295310fb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
