# Generated by Django 4.1.3 on 2022-12-02 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='rate',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rate',
            field=models.ManyToManyField(through='ads.Rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
