# Generated by Django 4.1.3 on 2022-12-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_value',
        ),
    ]
