# Generated by Django 4.1.3 on 2022-12-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_rating_rating_rating_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='rate',
        ),
    ]
