# Generated by Django 4.1.3 on 2022-12-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_alter_rating_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ads.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='Common', max_length=150),
        ),
    ]
